[package]
name = "charizhard"
version = "0.1.0"
authors = ["_index indexd@pm.me"]
edition = "2021"
resolver = "2"
rust-version = "1.81"

[[bin]]
name = "charizhard"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[build]
exclude = ["src/wireguard/**"]

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.4" }

# [[package.metadata.esp-idf-sys.extra_components]]
# remote_component = { name = "trombik/esp_wireguard", version = "0.9" }
# bindings_header = "src/wireguard/bindings.h"
# bindings_module = "wireguard"

[dependencies]
log = { version = "0.4.22", default-features = false }
esp-idf-svc = { version = "0.49.1", default-features = false, features = ["alloc", "std"] }
esp-idf-hal = "0.44.1"
embedded-hal = "1.0.0"
embedded-svc = "0.28.0"
heapless = "0.8.0"
anyhow = { version = "1.0.93", default-features = false }
base64 = "0.22.1"
serde = { version = "1.0.214", default-features = false, features = ["derive"] }
serde_urlencoded = "0.7.1"
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
once_cell = "1.20.2"

[build-dependencies]
embuild = "0.32.0"