[tasks.build-release]
command = "cargo"
args = ["build", "--release", "-vv"]

[tasks.convert-to-bin]
command = "esptool"
args = ["--chip", "esp32", "elf2image", "--output", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/xtensa-esp32-espidf/release/charizhard.bin", "C:/chhard/target/xtensa-esp32-espidf/release/charizhard"]

[tasks.write]
command = "esptool"
args = [
    "write_flash", "--encrypt", 
    "0x1000", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/xtensa-esp32-espidf/release/bootloader.bin",
    "0x10000", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/xtensa-esp32-espidf/release/partition-table.bin",
    "0x30000", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/xtensa-esp32-espidf/release/charizhard.bin"
]

[tasks.monitor-windows]
command = "putty"
args = ["-serial", "${COM_PORT}", "-sercfg", "115200,8,n,1,N"]

[tasks.monitor-linux]
command = "screen"
args = ["/dev/${ttyUSB}", "115200"]

[tasks.flash]
dependencies = [
    "build-release",
    "convert-to-bin",
    "write",
]