[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "cargo make flash" # Select this runner for espflash v3.x.x
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"
CARGO_WORKSPACE_DIR = { value = "", relative = true }

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"

[alias]
flash="make flash"
f = "make flash"
c = "make config"
config = "make config"
e = "make erase"
erase = "make erase"
m = "make monitor"
monitor = "make monitor"
# (Keep yourself safe)
kys = "make kys"