name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      run: |
        cd /
        cargo install espup@0.11.0
        espup install
        cd $GITHUB_WORKSPACE
        git clone https://github.com/indexds/charizhard chhard
        cd $GITHUB_WORKSPACE/chhard
        cargo install cargo-make
        cargo ci