name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      run: |
        pip install --upgrade platformio
        cargo install cargo-pio cargo-generate espflash ldproxy espup@0.11.0
        espup install
        rustup override set esp
        cargo build --release