name: Continuous Integration for ESP32

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "**/logo"
      - "**/schematic"
      - "LICENCE"
      - "logo.png"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

# Fail on any warning (clippy)
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      

      - name: Install ESP32 Toolchain with espup
        run: |
          curl -L https://github.com/esp-rs/embuild/releases/latest/download/ldproxy-x86_64-unknown-linux-gnu.zip -o $HOME/.cargo/bin/ldproxy.zip
          unzip "$HOME/.cargo/bin/ldproxy.zip" -d "$HOME/.cargo/bin/"
          chmod a+x $HOME/.cargo/bin/ldproxy
          curl -L https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu -o espup
          chmod a+x espup
          ./espup install

      - name: Format
        run: cargo fmt

      - name: Audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Set ESP32 Environment Variables
        run: |
          source $HOME/export-esp.sh  # Source environment variables
          export ESP_IDF_PATH=$HOME/.espressif/esp-idf
          echo "ESP_IDF_PATH set to $ESP_IDF_PATH"

      - name: Fmt Check
        run: cargo fmt -- --check

      - name: Run Audit
        run: |
          cargo install cargo-audit
          cargo audit -- --deny warnings

      - name: Clippy
        run: cargo clippy -- --deny warnings

      - name: Enable Caching
        uses: Swatinem/rust-cache@v2

      - name: Build Project for ESP32
        run: RUST_BACKTRACE=full cargo build --release --target xtensa-esp32-espidf