# name: Rust
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         submodules: 'recursive'
#     - name: esp-idf build
#       run: |
#         cd /
#         sudo curl -L https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu -o espup
#         sudo chmod a+x espup
#         /espup install
#         cd $GITHUB_WORKSPACE
#         git clone https://github.com/indexds/charizhard chhard
#         cd $GITHUB_WORKSPACE/chhard
#         cargo build --release